# Generated by Django 2.0.4 on 2018-04-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavern', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='drinks',
            field=models.CharField(max_length=100),
        ),
    ]
