# Generated by Django 2.0.4 on 2018-04-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavern', '0002_auto_20180425_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='drinks',
            new_name='drink_name',
        ),
        migrations.AddField(
            model_name='drink',
            name='strength',
            field=models.IntegerField(default=0),
        ),
    ]
