# Generated by Django 2.0.4 on 2018-04-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavern', '0004_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='charisma',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='status',
            name='strength',
            field=models.IntegerField(default=50),
        ),
    ]
