# Generated by Django 2.0.4 on 2018-04-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavern', '0005_auto_20180426_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='price',
            field=models.IntegerField(default=1),
        ),
    ]
