# Generated by Django 2.0.4 on 2018-04-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavern', '0006_drink_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='drink_desc',
            field=models.CharField(default='...', max_length=250),
        ),
    ]
